### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by pjconnors** [argyleink/ragrid#4]
Have you done much browser support testing yet?
Would it basically be "any browser that can support custom attributes would also support flex" and vice versa?

**Comment by argyleink** [comment]
The style of [selectors RAGrid uses are pretty old](http://caniuse.com/#feat=css-sel2), flexbox is much newer. The support for flexbox in RAGrid is only supporting the [latest form of flex](http://caniuse.com/#feat=flexbox) and none of it's previous versions. So yep, any browser that supports flexbox is g2g 🙂
